core/accounts/urls.py
from django.urls import path

from accounts.views import LoginView, SignupView

app_name = "accounts"

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("signup/", SignupView.as_view(), name="signup"),
]

core/blog/urls.py
from django.urls import path
from .views import BlogView, SingleView, BlogSearch

app_name = "blog"

urlpatterns = [
    path('', BlogView.as_view(), name='blog'),
    path('post/<int:pid>/', SingleView.as_view(), name='single'),
    path('search/', BlogSearch.as_view(), name='search'),
    path('category/<str:cat_name>/', BlogView.as_view(), name='category'),
    path('tag/<str:tag_name>/', BlogView.as_view(), name='tag'),
    path('author/<str:author_username>/', BlogView.as_view(), name='author'),
    path('date/<str:date>/', BlogView.as_view(), name='date'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("blog/", include("blog.urls")),
    path("shop/", include("shop.urls")),
    path("", include("website.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/shop/urls.py
from django.urls import path

from shop.views import ProductListView, SingleProductView, CartView, CheckoutView, ConfirmationView

app_name = "shop"

urlpatterns = [
    path("", ProductListView.as_view(), name="shop"),
    path("product/", SingleProductView.as_view(), name="product"),
    path("cart/", CartView.as_view(), name="cart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("confirmation/", ConfirmationView.as_view(), name="confirmation"),
]

core/website/urls.py
from django.urls import path

from website.views import IndexView, AboutView, ContactView, NewsletterView

app_name = "website"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("newsletter/", NewsletterView.as_view(), name="newsletter"),
]

core/website/models.py
from django.db import models


class Contact(models.Model):
    """
    This class is for users to contact the admin
    """

    name = models.CharField(max_length=60)
    email = models.EmailField()
    subject = models.CharField(max_length=60)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return self.name


class Newsletter(models.Model):
    """
    This class is for website newsletter
    """

    email = models.EmailField()

    def __str__(self):
        return self.email

core/website/forms.py
from django import forms
from website.models import Contact, Newsletter


class ContactForm(forms.ModelForm):
    """
    The ContactForm model is used for processing a contact form. It is a ModelForm that is based on the Contact model
    """

    class Meta:
        model = Contact
        fields = "__all__"


class NewsletterForm(forms.ModelForm):
    """
    The NewsletterForm model is used for processing a newsletter subscription form
    """

    class Meta:
        model = Newsletter
        fields = "__all__"

core/website/views.py
from django.views.generic.base import TemplateView
from django.views.generic import FormView
from django.views import View
from django.shortcuts import render
from django.contrib import messages
from website.forms import ContactForm, NewsletterForm
from django.http.response import HttpResponseRedirect

class IndexView(TemplateView):
    template_name = "website/index.html"


class AboutView(TemplateView):
    template_name = "website/about.html"


# class ContactView(View):
#     def get(self, request):
#         form = ContactForm()
#         return render(request, "website/contact.html", {"form": form})

#     def post(self, request):
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.add_message(
#                 request, messages.SUCCESS, "Your ticket has been successfully sent"
#             )
#         else:
#             messages.add_message(request, messages.ERROR, "Your ticket was not sent")
#         return render(request, "website/contact.html", {"form": form})

class ContactView(FormView):
    template_name = 'website/contact.html'
    form_class = ContactForm
    success_url = '/contact/'  

    def form_valid(self, form):
        form.save()
        messages.add_message(
            self.request, messages.SUCCESS, "Your ticket has been successfully sent"
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, "Your ticket was not sent")
        return super().form_invalid(form)

class NewsletterView(View):
    def post(self, request):
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/")
        else:
            return HttpResponseRedirect("/")

core/templates/website/contact.html
{% load static %}
<!doctype html>
<html lang="zxx">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>الکتروفریکس - ارتباط با ما</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
      <div class="container">
          <div class="row align-items-center justify-content-center">
              <div class="col-lg-12">
                  <nav class="navbar navbar-expand-lg navbar-light">
                      <a class="navbar-brand" href="{% url 'website:index' %}"> <img src="{% static 'img/logo.png' %}" alt="logo"> </a>
                      <button class="navbar-toggler" type="button" data-toggle="collapse"
                          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                          aria-expanded="false" aria-label="Toggle navigation">
                          <span class="menu_icon"><i class="fas fa-bars"></i></span>
                      </button>

                      <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                          <ul class="navbar-nav">
                              <li class="nav-item">
                                  <a class="nav-link" href="{% url 'website:index' %}">صفحه اصلی</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link" href="{% url 'website:about' %}">درباره</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link" href="{% url 'shop:shop' %}">فروشگاه</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link" href="{% url 'blog:blog' %}">وبلاگ</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link" href="{% url 'website:contact' %}">ارتباط با ما</a>
                              </li>
                          </ul>
                      </div>
                      <div class="hearer_icon d-flex align-items-center">
                          <a id="search_1" href="javascript:void(0)">
                              <i class="ti-search"></i>
                          </a>
                          <a href="{% url 'shop:cart' %}">
                              <i class="flaticon-shopping-cart-black-shape"></i>
                          </a>
                          <a href="{% url 'accounts:login' %}">
                              <i class="ti-user"></i>
                          </a>
                      </div>
                  </nav>
              </div>
          </div>
      </div>
      <div class="search_input" id="search_input_box">
          <div class="container ">
              <form class="d-flex justify-content-between search-inner">
                  <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                  <button type="submit" class="btn"></button>
                  <span class="ti-close" id="close_search" title="Close Search"></span>
              </form>
          </div>
      </div>
  </header>
  <!-- Header part end-->

    <!-- breadcrumb part start-->
    <section class="breadcrumb_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2>ارتباط با ما</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->

  <!-- ================ contact section start ================= -->
  <section class="contact-section section_padding">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="contact-title">با ما در تماس باشید</h2>
        </div>
        <div class="col-lg-8">
          <form class="form-contact contact_form" action="{% url 'website:contact' %}" method="post" id="contactForm" novalidate="novalidate">
            {% csrf_token %}
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" placeholder='Enter Message'></textarea>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control" name="name" id="name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" placeholder='Enter your name'>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <input class="form-control" name="email" id="email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" placeholder='Enter email address'>
                </div>
              </div>
              <div class="col-12">
                <div class="form-group">
                  <input class="form-control" name="subject" id="subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Subject'" placeholder='Enter Subject'>
                </div>
              </div>
            </div>
            <div class="form-group mt-3">
              <button type="submit" class="btn_3 button-contactForm">Send Message</button>
            </div>
          </form>
        </div>
        <div class="col-lg-4">
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-home"></i></span>
            <div class="media-body">
              <h3>ایران - تهران</h3>
              <p>تهران مرکزی</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-tablet"></i></span>
            <div class="media-body">
              <h3>+98 902 194 4825</h3>
              <p>شنبه تا چهارشنبه 9 صبح تا 6 بعد از ظهر</p>
            </div>
          </div>
          <div class="media contact-info">
            <span class="contact-info__icon"><i class="ti-email"></i></span>
            <div class="media-body">
              <h3>electrofreaks002@gmail.com</h3>
              <p>!درخواست خود را در هر زمان برای ما ارسال کنید</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ================ contact section end ================= -->

  <!--::footer_part start::-->
  <footer class="footer_part">
    <div class="footer_iner">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-lg-8">
                    <div class="footer_logo">
                        <a href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt="#"></a>
                    </div>
                    <div class="footer_menu">
                        <div class="footer_menu_item">
                            <p><a href="{% url 'website:index' %}">صفحه اصلی</a></p>
                            <p><a href="{% url 'website:about' %}">درباره</a></p>
                            <p><a href="{% url 'shop:shop' %}">فروشگاه</a></p>
                            <p><a href="{% url 'blog:blog' %}">وبلاگ</a></p>
                            <p><a href="{% url 'website:contact' %}">ارتباط با ما</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="social_icon">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-google-plus-g"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="copyright_part">
        <div class="container">
            <div class="row ">
                <div class="col-lg-12">
                    <div class="copyright_text">
                        <P>Developed by <a href="https://amirhamidi.pythonanywhere.com/">Amir Hamidi</a> | Designed by <a href="https://colorlib.com">Colorlib</a></P>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--::footer_part end::-->

    <!-- jquery plugins here-->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <!-- particles js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- slick js -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

core/templates/website/index.html
{% load static %}
<!doctype html>
<html lang="zxx">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>فروشگاه اینترنتی الکتروفریکس</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="{% url 'website:index' %}"> <img src="{% static 'img/logo.png' %}" alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'website:index' %}">صفحه اصلی</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'website:about' %}">درباره</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'shop:shop' %}">فروشگاه</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'blog:blog' %}">وبلاگ</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'website:contact' %}">ارتباط با ما</a>
                                </li>
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex align-items-center">
                            <a id="search_1" href="javascript:void(0)">
                                <i class="ti-search"></i>
                            </a>
                            <a href="{% url 'shop:cart' %}">
                                <i class="flaticon-shopping-cart-black-shape"></i>
                            </a>
                            <a href="{% url 'accounts:login' %}">
                                <i class="ti-user"></i>
                            </a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container ">
                <form class="d-flex justify-content-between search-inner">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="ti-close" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- Header part end-->

    <!-- banner part start-->
    <section class="banner_part">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-md-5">
                    <div class="banner_text">
                        <div class="banner_text_iner">
                            <h1>الکتروفریکس</h1>
                            <a href="{% url 'shop:shop' %}" class="btn_1">خرید کنید</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="banner_img">
            <img src="{% static 'img/banner.png' %}" alt="#" class="img-fluid">
            <img src="{% static 'img/banner_pattern.png' %} " alt="#" class="pattern_img img-fluid">
        </div>
    </section>
    <!-- banner part start-->

    <!-- product list start-->
    <section class="single_product_list">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="single_product_iner">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-lg-6 col-sm-6">
                                <div class="single_product_img">
                                    <img src="{% static 'img/single_product_1.png' %}" class="img-fluid" alt="#">
                                    <img src="{% static 'img/product_overlay.png' %}" alt="#" class="product_overlay img-fluid">
                                </div>
                            </div>
                            <div class="col-lg-5 col-sm-6">
                                <div class="single_product_content">
                                    <h5>Started from $10</h5>
                                    <h2> <a href="{% url 'shop:product' %}">Printed memory foam 
                                        brief modern throw 
                                        pillow case</a> </h2>
                                    <a href="{% url 'shop:shop' %}" class="btn_3">Explore Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="single_product_iner">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-lg-6 col-sm-6">
                                <div class="single_product_img">
                                    <img src="{% static 'img/single_product_2.png' %}" class="img-fluid" alt="#">
                                    <img src="{% static 'img/product_overlay.png' %}" alt="#" class="product_overlay img-fluid">
                                </div>
                            </div>
                            <div class="col-lg-5 col-sm-6">
                                <div class="single_product_content">
                                    <h5>Started from $10</h5>
                                    <h2> <a href="{% url 'shop:product' %}">Printed memory foam 
                                        brief modern throw 
                                        pillow case</a> </h2>
                                    <a href="{% url 'shop:shop' %}" class="btn_3">Explore Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="single_product_iner">
                        <div class="row align-items-center justify-content-between">
                            <div class="col-lg-6 col-sm-6">
                                <div class="single_product_img">
                                    <img src="{% static 'img/single_product_3.png' %}" class="img-fluid" alt="#">
                                    <img src="{% static 'img/product_overlay.png' %}" alt="#" class="product_overlay img-fluid">
                                </div>
                            </div>
                            <div class="col-lg-5 col-sm-6">
                                <div class="single_product_content">
                                    <h5>Started from $10</h5>
                                    <h2> <a href="{% url 'shop:product' %}">Printed memory foam 
                                            brief modern throw 
                                            pillow case</a> </h2>
                                    <a href="{% url 'shop:shop' %}" class="btn_3">Explore Now</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- product list end-->


    <!-- trending item start-->
    <section class="trending_items">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section_tittle text-center">
                        <h2>Trending Items</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-sm-6">
                    <div class="single_product_item">
                        <div class="single_product_item_thumb">
                            <img src="{% static 'img/tranding_item/tranding_item_1.png' %}" alt="#" class="img-fluid">
                        </div>
                        <h3> <a href="{% url 'shop:product' %}">Cervical pillow for airplane
                        car office nap pillow</a> </h3>
                        <p>From $5</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single_product_item">
                        <img src="{% static 'img/tranding_item/tranding_item_2.png' %}" alt="#" class="img-fluid">
                        <h3> <a href="{% url 'shop:product' %}">Foam filling cotton slow rebound pillows</a> </h3>
                        <p>From $5</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single_product_item">
                        <img src="{% static 'img/tranding_item/tranding_item_3.png' %}" alt="#" class="img-fluid">
                        <h3> <a href="{% url 'shop:product' %}">Memory foam filling cotton Slow rebound pillows</a> </h3>
                        <p>From $5</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single_product_item">
                        <img src="{% static 'img/tranding_item/tranding_item_4.png' %}" alt="#" class="img-fluid">
                        <h3> <a href="{% url 'shop:product' %}">Cervical pillow for airplane
                        car office nap pillow</a> </h3>
                        <p>From $5</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single_product_item">
                        <img src="{% static 'img/tranding_item/tranding_item_5.png' %}" alt="#" class="img-fluid">
                        <h3> <a href="{% url 'shop:product' %}">Foam filling cotton slow rebound pillows</a> </h3>
                        <p>From $5</p>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <div class="single_product_item">
                        <img src="{% static 'img/tranding_item/tranding_item_6.png' %}" alt="#" class="img-fluid">
                        <h3> <a href="{% url 'shop:product' %}">Memory foam filling cotton Slow rebound pillows</a> </h3>
                        <p>From $5</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- trending item end-->

    {% include 'website/client-review.html' %}

    {% include 'website/feature.html' %}

    {% include 'website/newsletter.html' %}

    {% include 'website/footer.html' %}

    <!-- jquery plugins here-->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- magnific popup js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- carousel js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- slick js -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

core/templates/website/newsletter.html
<!-- subscribe part here -->
<section class="subscribe_part section_padding">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="subscribe_part_content">
                    <h2>Get promotions & updates!</h2>
                    <p>Seamlessly empower fully researched growth strategies and interoperable internal or “organic” sources credibly innovate granular internal .</p>
                    <div class="subscribe_form">
                        <form action="{% url 'website:newsletter' %}" method="post">
                            {% csrf_token %}
                            <input type="email" name="email" placeholder="Enter your mail">
                            <button type="submit" class="btn_1">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- subscribe part end -->