core/accounts/urls.py
from django.urls import path

from accounts.views import LoginView, SignupView

app_name = "accounts"

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("signup/", SignupView.as_view(), name="signup"),
]

core/blog/urls.py
from django.urls import path
from .views import BlogView, SingleView, BlogSearch

app_name = "blog"

urlpatterns = [
    path('', BlogView.as_view(), name='blog'),
    path('post/<int:pid>/', SingleView.as_view(), name='single'),
    path('search/', BlogSearch.as_view(), name='search'),
    path('category/<str:cat_name>/', BlogView.as_view(), name='category'),
    path('tag/<str:tag_name>/', BlogView.as_view(), name='tag'),
    path('author/<str:author_username>/', BlogView.as_view(), name='author'),
    path('date/<str:date>/', BlogView.as_view(), name='date'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("blog/", include("blog.urls")),
    path("shop/", include("shop.urls")),
    path("", include("website.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/shop/urls.py
from django.urls import path

from shop.views import ProductListView, SingleProductView, CartView, CheckoutView, ConfirmationView

app_name = "shop"

urlpatterns = [
    path("", ProductListView.as_view(), name="shop"),
    path("product/", SingleProductView.as_view(), name="product"),
    path("cart/", CartView.as_view(), name="cart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("confirmation/", ConfirmationView.as_view(), name="confirmation"),
]

core/website/urls.py
from django.urls import path

from website.views import IndexView, AboutView, ContactView, NewsletterView

app_name = "website"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("newsletter/", NewsletterView.as_view(), name="newsletter"),
]

core/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Category(models.Model):
    """
    This class is for creating categories
    """

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    This class is for adding posts to the blog
    """

    image = models.ImageField(upload_to="blog/", default="blog/default.jpg")
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    date = models.DateField(auto_now=True)

    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:single", kwargs={"pid": self.id})


class Comment(models.Model):
    """
    This class is for users to comments
    """

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from blog.models import Comment


class CommentForm(forms.ModelForm):
    """
    The CommentForm model is used for processing a Comment form. It is a ModelForm that is based on the Comment model
    """

    class Meta:
        model = Comment
        fields = ["post", "name", "email", "subject", "message"]

core/blog/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from datetime import datetime
from django.views import View

from blog.models import Category, Post, Comment
from blog.forms import CommentForm


class BlogView(View):
    def get(self, request, **kwargs):
        posts = Post.objects.filter(status=1)
        if kwargs.get("cat_name") != None:
            posts = posts.filter(category__name=kwargs["cat_name"])
        if kwargs.get("tag_name") != None:
            posts = posts.filter(tags__name__in=[kwargs['tag_name']])
        if kwargs.get("author_username") != None:
            posts = posts.filter(author__username=kwargs["author_username"])
        if kwargs.get("date") != None:
            date_str = kwargs["date"]
            date = datetime.strptime(date_str, '%Y-%m-%d').date()
            posts = posts.filter(date=date)
        posts = Paginator(posts, 20)
        try:
            page_number = request.GET.get("page")
            posts = posts.get_page(page_number)
        except PageNotAnInteger:
            posts = posts.get_page(1)
        except EmptyPage:
            posts = posts.get_page(1)
        context = {"posts": posts}
        return render(request, "blog/blog.html", context)


class SingleView(View):
    def get(self, request, pid):
        posts = Post.objects.filter(status=1)
        post = get_object_or_404(posts, pk=pid)
        post.counted_views += 1
        post.save()
        comments = Comment.objects.filter(post=post.id, approved=True)
        form = CommentForm
        context = {"post": post, "comments": comments, "form": form}
        return render(request, "blog/single-blog.html", context)

    def post(self, request, pid):
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(
                request, messages.SUCCESS, "نظر شما با موفقیت ارسال شد"
            )
        else:
            messages.add_message(request, messages.ERROR, "نظر شما ثبت نشد")
        return self.get(request, pid)


class BlogSearch(View):
    def get(self, request, **kwargs):
        posts = Post.objects.filter(status=1)
        if request.method == "GET":
            if s := request.GET.get("s"):
                posts = posts.filter(content__contains=s)
        context = {"posts": posts}
        return render(request, "blog/blog.html", context)

core/templates/blog/blog-categories.html
<aside class="single_sidebar_widget post_category_widget">
    <h4 class="widget_title">دسته بندی ها</h4>
    <ul class="list cat-list">
      {% for name, count in categories.items %}
       <li>
          <a href="{% url 'blog:category' cat_name=name %}" class="d-flex">
             <p>{{name}} ({{count}})</p>
          </a>
       </li>
       {% endfor %}
    </ul>
 </aside>

core/templates/blog/blog-newsletter.html
<aside class="single_sidebar_widget newsletter_widget">
    <h4 class="widget_title">خبرنامه</h4>
    <form action="{% url 'website:newsletter' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input type="email" class="form-control" name="email" placeholder='ایمیل' required>
        </div>
        <button class="button rounded-0 primary-bg text-white w-100 btn_1" type="submit">دنبال کردن</button>
    </form>
</aside>

core/templates/blog/blog.html
{% load static %}
{% load blog_tags %}
<!doctype html>
<html lang="zxx">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>الکتروفریکس - وبلاگ</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="{% url 'website:index' %}"> <img src="{% static 'img/logo.png' %}" alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'website:index' %}">صفحه اصلی</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'website:about' %}">درباره</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'shop:shop' %}">فروشگاه</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'blog:blog' %}">وبلاگ</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'website:contact' %}">ارتباط با ما</a>
                                </li>
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex align-items-center">
                            <a id="search_1" href="javascript:void(0)">
                                <i class="ti-search"></i>
                            </a>
                            <a href="{% url 'shop:cart' %}">
                                <i class="flaticon-shopping-cart-black-shape"></i>
                            </a>
                            <a href="{% url 'accounts:login' %}">
                                <i class="ti-user"></i>
                            </a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container ">
                <form class="d-flex justify-content-between search-inner">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="ti-close" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- Header part end-->

    <!-- breadcrumb part start-->
    <section class="breadcrumb_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2>وبلاگ</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->

    <!--================Blog Area =================-->
    <section class="blog_area section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                        {% for post in posts %}
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{post.image.url}}" alt="{{ post.title }}">
                                <a href="{% url 'blog:date' date=post.date %}" class="blog_item_date">
                                    <h3>{{post.published_date|date:"d"}}</h3>
                                    <p>{{post.published_date|date:"M"}}</p>
                                </a>
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'blog:single' pid=post.id %}">
                                    <h2>{{ post.title }}</h2>
                                </a>
                                <p>{{post.content|truncatewords:10}}</p>
                                <ul class="blog-info-link">
                                    <li><a href="{% url 'blog:author' author_username=post.author.username %}"><i class="far fa-user"></i>{{post.author.get_full_name}}</a></li>
                                    <li><a><i class="far fa-folder"></i></a>
                                    {% for cat in post.category.all %}
                                    <a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>{% if not forloop.last %} ,{% endif %}
                                    {% endfor %}
                                    </li>
                                    <li><a><i class="fa fa-tag"></i></a>
                                        {% for tag in post.tags.all %}
                                        <a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>{% if not forloop.last %} ,{% endif %}
                                        {% endfor %}
                                    </li>
                                    <li><a href="{% url 'blog:single' pid=post.id %}"><i class="far fa-eye"></i>{{post.counted_views}} views</a></li>
                                    <li><a href="{% url 'blog:single' pid=post.id %}"><i class="far fa-comments"></i>{{post.comments.count}} Comments</a></li>
                                </ul>
                            </div>
                        </article>
                        {% endfor %}

                        <nav class="blog-pagination justify-content-center d-flex">
                            <ul class="pagination">
                                {% if posts.has_previous %}
                                <li class="page-item">
                                    <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                                        <i class="ti-angle-left"></i>
                                    </a>
                                </li>
                                {% endif %}
                                {% for i in posts.paginator.page_range %}
                                {% if posts.number == i  %}
                                <li class="page-item">
                                    <a href="?page={{i}}" class="page-link">{{i}}</a>
                                </li>
                                {% endif %}
                                {% endfor %}
                                {% if posts.has_next %}
                                <li class="page-item">
                                    <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                                        <i class="ti-angle-right"></i>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        
                        {% include 'blog/blog-search.html' %}

                        {% categories %}

                        {% latest_posts %}
                        
                        {% tags %}

                        {% include 'blog/blog-newsletter.html' %}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->

    {% include 'website/footer.html' %}


    <!-- jquery plugins here-->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <!-- particles js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- slick js -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

core/templates/blog/single-blog.html
{% load static %}
{% load humanize %}
{% load blog_tags %}
<!doctype html>
<html lang="zxx">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>الکتروفریکس - {{ post.title }}</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="{% url 'website:index' %}"> <img src="{% static 'img/logo.png' %}" alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'website:index' %}">صفحه اصلی</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'website:about' %}">درباره</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'shop:shop' %}">فروشگاه</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'blog:blog' %}">وبلاگ</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'website:contact' %}">ارتباط با ما</a>
                                </li>
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex align-items-center">
                            <a id="search_1" href="javascript:void(0)">
                                <i class="ti-search"></i>
                            </a>
                            <a href="{% url 'shop:cart' %}">
                                <i class="flaticon-shopping-cart-black-shape"></i>
                            </a>
                            <a href="{% url 'accounts:login' %}">
                                <i class="ti-user"></i>
                            </a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container ">
                <form class="d-flex justify-content-between search-inner">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="ti-close" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- Header part end-->

    <!-- breadcrumb part start-->
    <section class="breadcrumb_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2>{{ post.title }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->
   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section_padding">
      <div class="container">
         <div class="row">
            <div class="col-lg-8 posts-list">
               <div class="single-post">
                  <div class="feature-img">
                     <img class="img-fluid" src="{% static 'img/blog/single_blog_1.png' %}" alt="">
                  </div>
                  <div class="blog_details">
                     <h2>
                        {{ post.title }}
                     </h2>
                     <ul class="blog-info-link">
                        <li><a href="{% url 'blog:author' author_username=post.author.username %}"><i class="far fa-user"></i>{{post.author.get_full_name}}</a></li>
                        <li><a><i class="far fa-folder"></i></a>
                        {% for cat in post.category.all %}
                        <a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a>{% if not forloop.last %} ,{% endif %}
                        {% endfor %}
                        </li>
                        <li><a><i class="fa fa-tag"></i></a>
                            {% for tag in post.tags.all %}
                            <a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>{% if not forloop.last %} ,{% endif %}
                            {% endfor %}
                        </li>
                        <li><a href="{% url 'blog:single' pid=post.id %}"><i class="far fa-eye"></i>{{post.counted_views}} views</a></li>
                        <li><a href="{% url 'blog:single' pid=post.id %}"><i class="far fa-comments"></i>{{post.comments.count}} Comments</a></li>
                    </ul>
                     <p class="excert">
                        {{ post.content }}
                     </p>
                     <div class="quote-wrapper">
                        <div class="quotes">
                           MCSE boot camps have its supporters and its detractors. Some people do not understand why you
                           should have to spend money on boot camp when you can get the MCSE study materials yourself at
                           a fraction of the camp price. However, who has the willpower to actually sit through a
                           self-imposed MCSE training.
                        </div>
                     </div>
                  </div>
               </div>

               <div class="blog-author">
                  <div class="media align-items-center">
                     <img src="{% static 'img/blog/author.png' %}" alt="">
                     <div class="media-body">
                        <a href="{% url 'blog:author' author_username=post.author.username %}">
                           <h4>{{post.author.get_full_name}}</h4>
                        </a>
                        <p>Second divided from form fish beast made. Every of seas all gathered use saying you're, he
                           our dominion twon Second divided from</p>
                     </div>
                  </div>
               </div>
               <div class="comments-area">
                  <h4>{{post.comments.count}} Comments</h4>
                  {% for comment in comments %}
                  <div class="comment-list">
                     <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                           <div class="thumb">
                              <img src="{% static 'img/comment/comment_1.png' %}" alt="">
                           </div>
                           <div class="desc">
                              <p class="comment">
                                 {{ comment.message }}
                              </p>
                              <div class="d-flex justify-content-between">
                                 <div class="d-flex align-items-center">
                                    <h5>
                                       <a>{{ comment.name }}</a>
                                    </h5>
                                    <p class="date">{{ comment.created_date|naturaltime }}</p>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  {% endfor %}
               </div>
               <div class="comment-form">
                  <h4>Leave a Reply</h4>
                  <form action="{% url 'blog:single' pid=post.id %}" method="post" class="form-contact comment_form">
                     {% csrf_token %}
                     <div class="row">
                       <input type="hidden" name="post" value={{post.id}}>
                       <div class="col-md-6 form-group">
                         <input name="name" type="text" class="form-control" placeholder="*اسم شما">
                       </div>
                       <div class="col-md-6 form-group">
                         <input name="email" type="text" class="form-control" placeholder="*ایمیل شما">
                       </div>
                     </div>
                     <div class="row">
                       <div class="col form-group">
                         <input name="subject" type="text" class="form-control" placeholder="موضوع">
                       </div>
                     </div>
                     <div class="row">
                       <div class="col form-group">
                         <textarea name="message" class="form-control" placeholder="*متن پیام"></textarea>
                       </div>
                     </div>
                     <div class="form-group mt-3">
                        <button type="submit" class="btn_3 button-contactForm">ارسال نظر</button>
                     </div>   
                   </form>
               </br>
                  {% if messages %}
                  {% for message in messages %}
                    <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
                  {% endfor %}
                {% endif %}
               </div>
            </div>
            <div class="col-lg-4">
               <div class="blog_right_sidebar">
                  
                  {% include 'blog/blog-search.html' %}

                  {% categories %}

                  {% latest_posts %}

                  {% tags %}

                  {% include 'blog/blog-newsletter.html' %}

               </div>
            </div>
         </div>
      </div>
   </section>
   <!--================Blog Area end =================-->

   {% include 'website/footer.html' %}

    <!-- jquery plugins here-->
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <!-- popper js -->
    <script src="{% static 'js/popper.min.js' %}"></script>
    <!-- bootstrap js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- easing js -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/swiper.min.js' %}"></script>
    <!-- swiper js -->
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <!-- particles js -->
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <!-- slick js -->
    <script src="{% static 'js/slick.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>
    <!-- custom js -->
    <script src="{% static 'js/custom.js' %}"></script>
</body>
</html>